// Regenerates lib/features/festivals/data/observance_calendar.g.dart from
// tool/observances.json.
//
//   dart run tool/generate_observances.dart
//
// The JSON is the source of truth: dates as published by Drik Panchang for
// New Delhi, each checked against a second panchang where one was available.
// Extend it a year at a time; the app shows nothing past the last date.
import 'dart:convert';
import 'dart:io';

void main() {
  final data =
      jsonDecode(File('tool/observances.json').readAsStringSync())
          as Map<String, Object?>;
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_observances.dart from')
    ..writeln('// tool/observances.json. Do not edit by hand.')
    ..writeln('//')
    ..writeln('// Source: ${data['source']}'.replaceAll('\n', ' '))
    ..writeln()
    ..writeln("import '../domain/observance.dart';")
    ..writeln()
    ..writeln('const List<Observance> observanceCalendar = [');

  String slug(String name) => name
      .toLowerCase()
      .replaceAll(' ekadashi', '')
      .replaceAll(RegExp('[^a-z]+'), '-');

  final rows = <(String, String)>[];
  for (final e in (data['ekadashi']! as List).cast<Map<String, Object?>>()) {
    final vaishnava = e['vaishnavaDate'] as String?;
    rows.add((
      e['date']! as String,
      "  Observance(id: 'ekadashi.${slug(e['name']! as String)}', "
          "kind: ObservanceKind.ekadashi, start: '${e['date']}'"
          "${vaishnava == null ? '' : ", vaishnavaDay: '$vaishnava'"}),",
    ));
  }
  for (final f in (data['festivals']! as List).cast<Map<String, Object?>>()) {
    final id = f['id']! as String;
    final end = f['end'] as String?;
    final kind = id.endsWith('-month')
        ? 'ObservanceKind.period'
        : 'ObservanceKind.festival';
    rows.add((
      f['start']! as String,
      "  Observance(id: '$id', kind: $kind, start: '${f['start']}'"
          "${end == null ? '' : ", end: '$end'"}),",
    ));
  }
  rows.sort((a, b) => a.$1.compareTo(b.$1));
  for (final row in rows) {
    out.writeln(row.$2);
  }
  out.writeln('];');

  File(
    'lib/features/festivals/data/observance_calendar.g.dart',
  ).writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${rows.length} observances.');
}
