// GENERATED by tool/generate_observances.dart from
// tool/observances.json. Do not edit by hand.
//
// Source: Drik Panchang (drikpanchang.com), geoname-id=1261481 (New Delhi). Ekadashi: /vrats/ekadashidates.html?year=YYYY. Festivals: /festivals/month/festivals-<month>.html?year=YYYY, /navratri/ashwin-shardiya-navratri-dates.html, /navratri/chaitra-vasant-navratri-dates.html, /festivals/holi/festivals-holika-dahan-timings.html, /dashavatara/lord-krishna/krishna-janmashtami-date-time.html. Cross-checked with mPanchang Ekadashi list (New Delhi), AstroSage Indian Calendar (2026-2028), and Prokerala Hindu Calendar (2026-2027). Fetched 2026-10-01.

import '../domain/observance.dart';

const List<Observance> observanceCalendar = [
  Observance(
    id: 'ekadashi.indira',
    kind: ObservanceKind.ekadashi,
    start: '2026-10-06',
  ),
  Observance(
    id: 'sharad-navratri',
    kind: ObservanceKind.festival,
    start: '2026-10-11',
    end: '2026-10-19',
  ),
  Observance(
    id: 'dussehra',
    kind: ObservanceKind.festival,
    start: '2026-10-20',
  ),
  Observance(
    id: 'ekadashi.papankusha',
    kind: ObservanceKind.ekadashi,
    start: '2026-10-22',
  ),
  Observance(
    id: 'kartik-month',
    kind: ObservanceKind.period,
    start: '2026-10-27',
    end: '2026-11-24',
  ),
  Observance(
    id: 'ekadashi.rama',
    kind: ObservanceKind.ekadashi,
    start: '2026-11-05',
  ),
  Observance(id: 'diwali', kind: ObservanceKind.festival, start: '2026-11-08'),
  Observance(
    id: 'ekadashi.devutthana',
    kind: ObservanceKind.ekadashi,
    start: '2026-11-20',
    vaishnavaDay: '2026-11-21',
  ),
  Observance(
    id: 'guru-nanak-jayanti',
    kind: ObservanceKind.festival,
    start: '2026-11-24',
  ),
  Observance(
    id: 'kartik-purnima',
    kind: ObservanceKind.festival,
    start: '2026-11-24',
  ),
  Observance(
    id: 'ekadashi.utpanna',
    kind: ObservanceKind.ekadashi,
    start: '2026-12-04',
  ),
  Observance(
    id: 'ekadashi.mokshada',
    kind: ObservanceKind.ekadashi,
    start: '2026-12-20',
  ),
  Observance(
    id: 'ekadashi.saphala',
    kind: ObservanceKind.ekadashi,
    start: '2027-01-03',
  ),
  Observance(
    id: 'makar-sankranti',
    kind: ObservanceKind.festival,
    start: '2027-01-15',
  ),
  Observance(
    id: 'ekadashi.pausha-putrada',
    kind: ObservanceKind.ekadashi,
    start: '2027-01-18',
    vaishnavaDay: '2027-01-19',
  ),
  Observance(
    id: 'ekadashi.shattila',
    kind: ObservanceKind.ekadashi,
    start: '2027-02-02',
  ),
  Observance(
    id: 'vasant-panchami',
    kind: ObservanceKind.festival,
    start: '2027-02-11',
  ),
  Observance(
    id: 'ekadashi.jaya',
    kind: ObservanceKind.ekadashi,
    start: '2027-02-17',
  ),
  Observance(
    id: 'ekadashi.vijaya',
    kind: ObservanceKind.ekadashi,
    start: '2027-03-04',
  ),
  Observance(
    id: 'maha-shivaratri',
    kind: ObservanceKind.festival,
    start: '2027-03-06',
  ),
  Observance(
    id: 'ekadashi.amalaki',
    kind: ObservanceKind.ekadashi,
    start: '2027-03-18',
  ),
  Observance(id: 'holi', kind: ObservanceKind.festival, start: '2027-03-22'),
  Observance(
    id: 'ekadashi.papamochani',
    kind: ObservanceKind.ekadashi,
    start: '2027-04-02',
  ),
  Observance(
    id: 'chaitra-navratri',
    kind: ObservanceKind.festival,
    start: '2027-04-07',
    end: '2027-04-15',
  ),
  Observance(
    id: 'ram-navami',
    kind: ObservanceKind.festival,
    start: '2027-04-15',
  ),
  Observance(
    id: 'ekadashi.kamada',
    kind: ObservanceKind.ekadashi,
    start: '2027-04-17',
  ),
  Observance(
    id: 'mahavir-jayanti',
    kind: ObservanceKind.festival,
    start: '2027-04-19',
  ),
  Observance(
    id: 'hanuman-jayanti',
    kind: ObservanceKind.festival,
    start: '2027-04-20',
  ),
  Observance(
    id: 'ekadashi.varuthini',
    kind: ObservanceKind.ekadashi,
    start: '2027-05-02',
  ),
  Observance(
    id: 'ekadashi.mohini',
    kind: ObservanceKind.ekadashi,
    start: '2027-05-16',
  ),
  Observance(
    id: 'ekadashi.apara',
    kind: ObservanceKind.ekadashi,
    start: '2027-06-01',
  ),
  Observance(
    id: 'ekadashi.nirjala',
    kind: ObservanceKind.ekadashi,
    start: '2027-06-14',
  ),
  Observance(
    id: 'ekadashi.yogini',
    kind: ObservanceKind.ekadashi,
    start: '2027-06-30',
  ),
  Observance(
    id: 'ekadashi.devshayani',
    kind: ObservanceKind.ekadashi,
    start: '2027-07-14',
  ),
  Observance(
    id: 'guru-purnima',
    kind: ObservanceKind.festival,
    start: '2027-07-18',
  ),
  Observance(
    id: 'shravan-month',
    kind: ObservanceKind.period,
    start: '2027-07-19',
    end: '2027-08-17',
  ),
  Observance(
    id: 'ekadashi.kamika',
    kind: ObservanceKind.ekadashi,
    start: '2027-07-29',
    vaishnavaDay: '2027-07-30',
  ),
  Observance(
    id: 'ekadashi.shravana-putrada',
    kind: ObservanceKind.ekadashi,
    start: '2027-08-12',
  ),
  Observance(
    id: 'raksha-bandhan',
    kind: ObservanceKind.festival,
    start: '2027-08-17',
  ),
  Observance(
    id: 'krishna-janmashtami',
    kind: ObservanceKind.festival,
    start: '2027-08-25',
  ),
  Observance(
    id: 'ekadashi.aja',
    kind: ObservanceKind.ekadashi,
    start: '2027-08-28',
  ),
  Observance(
    id: 'ganesh-chaturthi',
    kind: ObservanceKind.festival,
    start: '2027-09-04',
  ),
  Observance(
    id: 'ekadashi.parsva',
    kind: ObservanceKind.ekadashi,
    start: '2027-09-11',
  ),
  Observance(
    id: 'ekadashi.indira',
    kind: ObservanceKind.ekadashi,
    start: '2027-09-26',
  ),
  Observance(
    id: 'sharad-navratri',
    kind: ObservanceKind.festival,
    start: '2027-09-30',
    end: '2027-10-08',
  ),
  Observance(
    id: 'dussehra',
    kind: ObservanceKind.festival,
    start: '2027-10-09',
  ),
  Observance(
    id: 'ekadashi.papankusha',
    kind: ObservanceKind.ekadashi,
    start: '2027-10-11',
  ),
  Observance(
    id: 'kartik-month',
    kind: ObservanceKind.period,
    start: '2027-10-16',
    end: '2027-11-14',
  ),
  Observance(
    id: 'ekadashi.rama',
    kind: ObservanceKind.ekadashi,
    start: '2027-10-25',
    vaishnavaDay: '2027-10-26',
  ),
  Observance(id: 'diwali', kind: ObservanceKind.festival, start: '2027-10-29'),
  Observance(
    id: 'ekadashi.devutthana',
    kind: ObservanceKind.ekadashi,
    start: '2027-11-10',
  ),
  Observance(
    id: 'guru-nanak-jayanti',
    kind: ObservanceKind.festival,
    start: '2027-11-14',
  ),
  Observance(
    id: 'kartik-purnima',
    kind: ObservanceKind.festival,
    start: '2027-11-14',
  ),
  Observance(
    id: 'ekadashi.utpanna',
    kind: ObservanceKind.ekadashi,
    start: '2027-11-24',
  ),
  Observance(
    id: 'ekadashi.mokshada',
    kind: ObservanceKind.ekadashi,
    start: '2027-12-09',
  ),
  Observance(
    id: 'ekadashi.saphala',
    kind: ObservanceKind.ekadashi,
    start: '2027-12-23',
  ),
  Observance(
    id: 'ekadashi.pausha-putrada',
    kind: ObservanceKind.ekadashi,
    start: '2028-01-08',
  ),
  Observance(
    id: 'makar-sankranti',
    kind: ObservanceKind.festival,
    start: '2028-01-15',
  ),
  Observance(
    id: 'ekadashi.shattila',
    kind: ObservanceKind.ekadashi,
    start: '2028-01-22',
  ),
  Observance(
    id: 'vasant-panchami',
    kind: ObservanceKind.festival,
    start: '2028-01-31',
  ),
  Observance(
    id: 'ekadashi.jaya',
    kind: ObservanceKind.ekadashi,
    start: '2028-02-06',
    vaishnavaDay: '2028-02-07',
  ),
  Observance(
    id: 'ekadashi.vijaya',
    kind: ObservanceKind.ekadashi,
    start: '2028-02-20',
    vaishnavaDay: '2028-02-21',
  ),
  Observance(
    id: 'maha-shivaratri',
    kind: ObservanceKind.festival,
    start: '2028-02-23',
  ),
  Observance(
    id: 'ekadashi.amalaki',
    kind: ObservanceKind.ekadashi,
    start: '2028-03-07',
  ),
  Observance(id: 'holi', kind: ObservanceKind.festival, start: '2028-03-11'),
  Observance(
    id: 'ekadashi.papamochani',
    kind: ObservanceKind.ekadashi,
    start: '2028-03-21',
  ),
  Observance(
    id: 'chaitra-navratri',
    kind: ObservanceKind.festival,
    start: '2028-03-27',
    end: '2028-04-03',
  ),
  Observance(
    id: 'ram-navami',
    kind: ObservanceKind.festival,
    start: '2028-04-03',
  ),
  Observance(
    id: 'ekadashi.kamada',
    kind: ObservanceKind.ekadashi,
    start: '2028-04-05',
    vaishnavaDay: '2028-04-06',
  ),
  Observance(
    id: 'mahavir-jayanti',
    kind: ObservanceKind.festival,
    start: '2028-04-07',
  ),
  Observance(
    id: 'hanuman-jayanti',
    kind: ObservanceKind.festival,
    start: '2028-04-09',
  ),
  Observance(
    id: 'ekadashi.varuthini',
    kind: ObservanceKind.ekadashi,
    start: '2028-04-20',
  ),
  Observance(
    id: 'ekadashi.mohini',
    kind: ObservanceKind.ekadashi,
    start: '2028-05-05',
  ),
  Observance(
    id: 'ekadashi.apara',
    kind: ObservanceKind.ekadashi,
    start: '2028-05-20',
  ),
  Observance(
    id: 'ekadashi.nirjala',
    kind: ObservanceKind.ekadashi,
    start: '2028-06-03',
  ),
  Observance(
    id: 'ekadashi.yogini',
    kind: ObservanceKind.ekadashi,
    start: '2028-06-18',
  ),
  Observance(
    id: 'ekadashi.devshayani',
    kind: ObservanceKind.ekadashi,
    start: '2028-07-02',
  ),
  Observance(
    id: 'guru-purnima',
    kind: ObservanceKind.festival,
    start: '2028-07-06',
  ),
  Observance(
    id: 'shravan-month',
    kind: ObservanceKind.period,
    start: '2028-07-07',
    end: '2028-08-05',
  ),
  Observance(
    id: 'ekadashi.kamika',
    kind: ObservanceKind.ekadashi,
    start: '2028-07-18',
  ),
  Observance(
    id: 'ekadashi.shravana-putrada',
    kind: ObservanceKind.ekadashi,
    start: '2028-08-01',
  ),
  Observance(
    id: 'raksha-bandhan',
    kind: ObservanceKind.festival,
    start: '2028-08-05',
  ),
  Observance(
    id: 'krishna-janmashtami',
    kind: ObservanceKind.festival,
    start: '2028-08-13',
  ),
  Observance(
    id: 'ekadashi.aja',
    kind: ObservanceKind.ekadashi,
    start: '2028-08-16',
    vaishnavaDay: '2028-08-17',
  ),
  Observance(
    id: 'ganesh-chaturthi',
    kind: ObservanceKind.festival,
    start: '2028-08-23',
  ),
  Observance(
    id: 'ekadashi.parsva',
    kind: ObservanceKind.ekadashi,
    start: '2028-08-30',
  ),
  Observance(
    id: 'ekadashi.indira',
    kind: ObservanceKind.ekadashi,
    start: '2028-09-15',
  ),
  Observance(
    id: 'sharad-navratri',
    kind: ObservanceKind.festival,
    start: '2028-09-19',
    end: '2028-09-26',
  ),
  Observance(
    id: 'dussehra',
    kind: ObservanceKind.festival,
    start: '2028-09-27',
  ),
  Observance(
    id: 'ekadashi.papankusha',
    kind: ObservanceKind.ekadashi,
    start: '2028-09-29',
  ),
  Observance(
    id: 'kartik-month',
    kind: ObservanceKind.period,
    start: '2028-10-04',
    end: '2028-11-02',
  ),
  Observance(
    id: 'ekadashi.rama',
    kind: ObservanceKind.ekadashi,
    start: '2028-10-14',
  ),
  Observance(id: 'diwali', kind: ObservanceKind.festival, start: '2028-10-17'),
  Observance(
    id: 'ekadashi.devutthana',
    kind: ObservanceKind.ekadashi,
    start: '2028-10-28',
    vaishnavaDay: '2028-10-29',
  ),
  Observance(
    id: 'guru-nanak-jayanti',
    kind: ObservanceKind.festival,
    start: '2028-11-02',
  ),
  Observance(
    id: 'kartik-purnima',
    kind: ObservanceKind.festival,
    start: '2028-11-02',
  ),
  Observance(
    id: 'ekadashi.utpanna',
    kind: ObservanceKind.ekadashi,
    start: '2028-11-12',
    vaishnavaDay: '2028-11-13',
  ),
  Observance(
    id: 'ekadashi.mokshada',
    kind: ObservanceKind.ekadashi,
    start: '2028-11-27',
  ),
  Observance(
    id: 'ekadashi.saphala',
    kind: ObservanceKind.ekadashi,
    start: '2028-12-12',
  ),
  Observance(
    id: 'ekadashi.pausha-putrada',
    kind: ObservanceKind.ekadashi,
    start: '2028-12-27',
  ),
];
