import '../../features/mantras/domain/mantra.dart';

/// Seeded on first launch. These can be edited and hidden but never deleted,
/// so a fresh install always has something to chant immediately.
abstract final class BuiltInMantras {
  static const List<Mantra> all = [
    Mantra(
      id: 'builtin.ram',
      name: 'Ram',
      devanagari: 'राम',
      transliteration: 'Rām',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 0,
    ),
    Mantra(
      id: 'builtin.radha',
      name: 'Radha',
      devanagari: 'राधा',
      transliteration: 'Rādhā',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 1,
    ),
    Mantra(
      id: 'builtin.om-namah-shivaya',
      name: 'Om Namah Shivaya',
      devanagari: 'ॐ नमः शिवाय',
      transliteration: 'Oṁ Namaḥ Śivāya',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 2,
    ),
    Mantra(
      id: 'builtin.om-hanumate-namah',
      name: 'Om Hanumate Namah',
      devanagari: 'ॐ हनुमते नमः',
      transliteration: 'Oṁ Hanumate Namaḥ',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 3,
    ),
    Mantra(
      id: 'builtin.hare-krishna',
      name: 'Hare Krishna',
      devanagari: 'हरे कृष्ण',
      transliteration: 'Hare Kṛṣṇa',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 4,
    ),
    Mantra(
      id: 'builtin.om-namo-bhagavate-vasudevaya',
      name: 'Om Namo Bhagavate Vasudevaya',
      devanagari: 'ॐ नमो भगवते वासुदेवाय',
      transliteration: 'Oṁ Namo Bhagavate Vāsudevāya',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 5,
    ),
    Mantra(
      id: 'builtin.gayatri',
      name: 'Gayatri Mantra',
      devanagari: 'ॐ भूर्भुवः स्वः तत्सवितुर्वरेण्यं\nभर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्',
      transliteration: 'Gāyatrī Mantra',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 6,
    ),
    Mantra(
      id: 'builtin.mahamrityunjaya',
      name: 'Mahamrityunjaya Mantra',
      devanagari: 'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम्\nउर्वारुकमिव बन्धनान् मृत्योर्मुक्षीय मामृतात्',
      transliteration: 'Mahāmṛtyuñjaya Mantra',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 7,
    ),
    // Sikh
    Mantra(
      id: 'builtin.waheguru',
      name: 'Waheguru',
      devanagari: 'वाहेगुरु',
      transliteration: 'Vāhegurū',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 8,
    ),
    Mantra(
      id: 'builtin.satnam-waheguru',
      name: 'Satnam Waheguru',
      devanagari: 'सतनाम वाहेगुरु',
      transliteration: 'Satnām Vāhegurū',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 9,
    ),
    Mantra(
      id: 'builtin.mool-mantar',
      name: 'Mool Mantar',
      devanagari: 'ੴ सति नामु करता पुरखु निरभउ निरवैरु\nअकाल मूरति अजूनी सैभं गुर प्रसादि',
      transliteration: 'Mūl Mantar',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 10,
    ),
    // Jain
    Mantra(
      id: 'builtin.navkar',
      name: 'Navkar Mantra',
      devanagari: 'णमो अरिहंताणं णमो सिद्धाणं णमो आयरियाणं\nणमो उवज्झायाणं णमो लोए सव्व साहूणं',
      transliteration: 'Ṇamokār Mantra',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 11,
    ),
    Mantra(
      id: 'builtin.om-hreem-arham-namah',
      name: 'Om Hreem Arham Namah',
      devanagari: 'ॐ ह्रीं अर्हं नमः',
      transliteration: 'Oṁ Hrīṁ Arhaṁ Namaḥ',
      malaSize: 108,
      isBuiltIn: true,
      sortOrder: 12,
    ),
  ];

  static Mantra get fallback => all.first;
}
